/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema;

/**
 *
 * @author VINICIUS
 */
public class Conversor extends javax.swing.JInternalFrame {

    double celsus;
    double farh;
    double kel;
    double x;
    double y;
    
    public Conversor() {
        initComponents();
     texto.setEditable(false);
      
        campo_1.setDocument(new Teclas());
       campo_2.setDocument(new Teclas());
       campo_3.setDocument(new Teclas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaoC = new javax.swing.JButton();
        botaoF = new javax.swing.JButton();
        botaoK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campo_1 = new javax.swing.JTextField();
        Farh = new javax.swing.JButton();
        campo_2 = new javax.swing.JTextField();
        celsius = new javax.swing.JButton();
        campo_3 = new javax.swing.JTextField();
        kelvin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        limpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("CONVERSOR TEMPERATURA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ESCOLHA UMAS DAS OPÇÕES ABAIXO CLICANDO NOS BOTÕES :");

        botaoC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoC.setText("° C  para °  F");
        botaoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCActionPerformed(evt);
            }
        });

        botaoF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoF.setText("°  F  para °  C");
        botaoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFActionPerformed(evt);
            }
        });

        botaoK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botaoK.setText("° C para  K");
        botaoK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoKActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CELSIUS ( °C )  PARA FAHRENHEIT ( °F ) :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FAHRENHEIT ( °F ) PARA CELSIUS ( °C ) :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CELSIUS (° C ) PARA KELVIN ( K ) : ");

        campo_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campo_1.setEnabled(false);

        Farh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Farh.setText("FAHRENHEIT");
        Farh.setEnabled(false);
        Farh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FarhActionPerformed(evt);
            }
        });

        campo_2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campo_2.setEnabled(false);

        celsius.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        celsius.setText("CELSIUS");
        celsius.setEnabled(false);
        celsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celsiusActionPerformed(evt);
            }
        });

        campo_3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        campo_3.setEnabled(false);

        kelvin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kelvin.setText("KELVIN");
        kelvin.setEnabled(false);
        kelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelvinActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CÁLCULO TEMPERATURA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        texto.setRows(5);
        texto.setEnabled(false);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        limpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        limpar.setText("LIMPAR");
        limpar.setEnabled(false);
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(botaoF)
                                .addGap(48, 48, 48)
                                .addComponent(botaoK, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(campo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Farh))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(campo_3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoC, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(botaoF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Farh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelvin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FarhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FarhActionPerformed
           celsus = Double.parseDouble(campo_1.getText());
        farh = (9 * celsus + 160)/5;
     
        texto.setText(" A conversão de Celsius para Fahrenhit usa a seguinte formula "+
                "\n F = ( 9 . C + 160 ) / 5 "+
                "\n Onde F = Fahrenhit , C = Celsius "+
                "\n -------------------------------------"+
                "\n F = ( 9 . "+celsus+" + 160 ) / 5 "+
                "\n F = ( "+(9*celsus+160)+" ) / 5 "+
                "\n F = "+Math.round(farh)+" ° F ");
        
         limpar.setEnabled(true);
        texto.setEnabled(true);
        
    }//GEN-LAST:event_FarhActionPerformed

    private void celsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celsiusActionPerformed
      
           farh = Double.parseDouble(campo_2.getText());
        x = farh - 32 ;
        y = x*5/9;
                
    texto.setText(" Para conversão de Fanhrenhit para Celsius usa a seguinte formula :"+
            "\n C = ( F - 32 ) . ( 5 / 9 )"+
            "\n C = Celsius , F = Fanhrenhit "+
            "\n -----------------------------------------"+
            "\n C = ( "+farh+" - 32 ) . ( 5 / 9 )"+
            "\n C = "+x+" . ( 5 /9 )"+
            "\n C = "+Math.round(y)+" ° C ");
     
    limpar.setEnabled(true);
    texto.setEnabled(true);
     
     
    }//GEN-LAST:event_celsiusActionPerformed

    private void kelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelvinActionPerformed
       
          kel = Double.parseDouble(campo_3.getText());
        celsus = kel + 273;
        texto.setText(" Sendo a conversão de Celsius para Kelvin usando a seguinte formula "+
                "\n K = C + 273 "+
                "\n K = Kelvin , C = Celsius "+
                "\n ------------------------------------"+
                "\n k = "+(long)kel+" + 273 "+
                "\n K = "+Math.round(celsus));
        
         limpar.setEnabled(true);
        texto.setEnabled(true);
         
         
    }//GEN-LAST:event_kelvinActionPerformed

    private void botaoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCActionPerformed
       
        Farh.setEnabled(true);
        campo_1.setEnabled(true);
        campo_1.requestFocus();
    }//GEN-LAST:event_botaoCActionPerformed

    private void botaoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFActionPerformed
        
        celsius.setEnabled(true);
        campo_2.setEnabled(true);
        campo_2.requestFocus();
    }//GEN-LAST:event_botaoFActionPerformed

    private void botaoKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoKActionPerformed
        
        kelvin.setEnabled(true);
        campo_3.setEnabled(true);
        campo_3.requestFocus();
    }//GEN-LAST:event_botaoKActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        
          // limpar campos de textos
        campo_1.setText("");
        campo_2.setText("");
        campo_3.setText("");
        texto.setText("");

        // desativar botões
        limpar.setEnabled(false);
        Farh.setEnabled(false);
        celsius.setEnabled(false);
        kelvin.setEnabled(false);

        // desativar campos de textos
        campo_1.setEnabled(false);
        campo_2.setEnabled(false);
        campo_3.setEnabled(false);
        texto.setEnabled(false);

    }//GEN-LAST:event_limparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Farh;
    private javax.swing.JButton botaoC;
    private javax.swing.JButton botaoF;
    private javax.swing.JButton botaoK;
    private javax.swing.JTextField campo_1;
    private javax.swing.JTextField campo_2;
    private javax.swing.JTextField campo_3;
    private javax.swing.JButton celsius;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelvin;
    private javax.swing.JButton limpar;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
